.PHONY: run-all-unit-tests run-backend-tests run-media-integrity-tests

run-all-unit-tests:
	go test -v ./src/backend/hypervisor/...
	go test -v ./src/backend/filesystem/...
	go test -v -short ./src/backend/discovery/...
	go test -v ./src/core/...

run-backend-tests:
	go test -v ./src/backend/hypervisor/...
	go test -v ./src/backend/filesystem/...
	go test -v -short ./src/backend/discovery/...

run-media-integrity-tests:
	go test -v ./src/backend/discovery/tests/
